import React from "react";
import Layout from "../../components/Layout/Layout";
import Papper from "../../components/Layout/Papper/Papper";

function DashboardPage() {

  const dataBreadcumb = [
    {
      name : "Dashboard",
      link : '/superadmin/dashboard'
    },
  ]
  return (
    <Papper
    dataBreadcumb={dataBreadcumb}
    > 

      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div>
        wkwkwk
      </div>
      <div className="bg-lime-200">
        wkwkwk
      </div>
    </Papper>
  );
}

export default DashboardPage;
